#https://dart.dev/tools/pub/automated-publishing
name: Publish lint_quido to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
 # push:
 #   branches:
 #     - main
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    #visit: https://github.com/dart-lang/ecosystem/blob/main/.github/workflows/publish.yaml
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@main
    with:
      sdk: 'dev'
